#!/usr/bin/env python3

"""
trackpoint-speed - Set TrackPoint speed.
License: BSD 3-Clause
Copyright (c) 2020, Mauro <mauro@sdf.org>
All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:
1. Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

__author__ = "Mauro"
__version__ = "0.0.1"
__license__ = "BSD3"


import shlex
import argparse
import subprocess as sp


def sh(cmd: str, get_output: bool = False) -> None:
    """
    Base sh call
    """
    cmd = shlex.split(cmd)
    if not get_output:
        return sp.call(cmd)
    elif get_output:
        return sp.check_output(cmd).decode("utf-8")


def xinput(cmd: str, get_output: bool = False) -> None:
    """
    Base xinput system call
    """
    return sh("xinput {}".format(cmd), get_output)


def set_prop(_id: int, prop: str, value: float) -> None:
    """
    Sets a xinput prop
    """
    xinput(f"--set-prop {_id} '{prop}' {value}")


def set_accel_speed(speed: float) -> None:
    """
    Sets the 'libinput Accel Speed' for the TrackPoint
    """
    output = xinput("list", True)
    output = [_ for _ in output.split("\n") if "TrackPoint" in _][0]
    output = [_ for _ in output.split("\t") if _.startswith("id=")][0]
    _id = int(output.replace("id=", ""))
    set_prop(_id, "libinput Accel Speed", speed)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Set TrackPoint speed.")
    parser.add_argument(
        "speed",
        type=str,
        nargs="?",
        help="Accel Speed value (can be negative as well.)",
    )
    args = parser.parse_args()
    if args.speed:
        set_accel_speed(args.speed)
    else:
        parser.print_help()
